In [1]:
import torch
import numpy as np

## Creating Tensors

In [2]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t)
print('Shape of t :',t.shape)
print('dtype of t :',t.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of t : torch.Size([2, 3])
dtype of t : torch.int64


In [3]:
# Create tensor withh specific dtype

t = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(t)
print('dtype of t :', t.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
dtype of t : torch.float32


In [4]:
# Have tensor on CPU (default)

t = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device="cpu")
print(t)
print('Is tensor t on GPU? ',t.is_cuda)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
Is tensor t on GPU?  False


## Attributes of Tensor

In [5]:
t = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32, device='cpu')

print('Dtype :', t.dtype)
print('Device on which tensor is :', t.device)
print('Shape :', t.shape)
print('Req  Grad :', t.requires_grad)

Dtype : torch.float32
Device on which tensor is : cpu
Shape : torch.Size([2, 3])
Req  Grad : False


## Tensor Initialization

In [6]:
x = torch.empty(size=(3, 3))
print('Empty Tensor (Random values) :\n', x)

Empty Tensor (Random values) :
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.zeros(size=(4,4))
print('Tensor having only zeros :\n', x)

Tensor having only zeros :
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [8]:
x = torch.ones(size=(5,6))
print('Tensor having only ones :\n', x)

Tensor having only ones :
 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [9]:
x = torch.eye(4)  # or torch.eye(size=(4,4))
print('Identity Tensor :\n', x)

Identity Tensor :
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [10]:
x = torch.arange(10)
print('Torch.arange :\n', x)

Torch.arange :
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [11]:
x = torch.linspace(start=0.1, end=1, steps=6)
print('Linspace (6 values between 0.1 and 1 with equal diff btw them) :\n', x)

Linspace (6 values between 0.1 and 1 with equal diff btw them) :
 tensor([0.1000, 0.2800, 0.4600, 0.6400, 0.8200, 1.0000])


In [12]:
x = torch.empty(size=(4,4)).normal_(mean=0, std=1)

# x = torch.empty(size=(4,4)).uniform_(0, 1)

print('Normally distributed empty Tensor :\n', x)

Normally distributed empty Tensor :
 tensor([[-1.0591, -0.2420,  0.1418, -0.7357],
        [ 0.7471, -0.1710,  0.2644, -0.6426],
        [-1.2417, -0.7207, -0.4643, -0.1480],
        [ 0.4440,  0.8576,  0.5315,  1.1076]])


In [13]:
x = torch.diag(torch.ones(3))
print('Tensor having one in its Diagonal, rest 0 :\n',x)

Tensor having one in its Diagonal, rest 0 :
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Initialize Tensors to other types (int, float, double)

In [14]:
t = torch.arange(4)
print('Tensor is :', t)
print('t.bool() :', t.bool())
print('t.short() :', t.short())
print('t.long() :', t.long())
print('t.half() :', t.half())  # Converts to float16
print('t.float() :', t.float())
print('t.double() :', t.double())

Tensor is : tensor([0, 1, 2, 3])
t.bool() : tensor([False,  True,  True,  True])
t.short() : tensor([0, 1, 2, 3], dtype=torch.int16)
t.long() : tensor([0, 1, 2, 3])
t.half() : tensor([0., 1., 2., 3.], dtype=torch.float16)
t.float() : tensor([0., 1., 2., 3.])
t.double() : tensor([0., 1., 2., 3.], dtype=torch.float64)


## Numpy & Tensor

In [15]:
arr = np.zeros((5, 5))
# print('5x5 Zeros Numpy Matrix :', arr)

# Tensor from Numpy
t = torch.from_numpy(arr)

# Numpy from Tensor
np_arr = t.numpy()

## Tensor Mathematical Operations

In [16]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

print('x :', x)
print('y :', y)

x : tensor([1, 2, 3])
y : tensor([9, 8, 7])


### Addition

In [17]:
print('x + y =', x+y)
print('torch.add(x, y) =', torch.add(x, y))
print('Inplace Addition x.add_(y) =', x.add_(y), 
      ' <- Value of x will be updated and y will remain same')
print('Now, value of x :', x)

x + y = tensor([10, 10, 10])
torch.add(x, y) = tensor([10, 10, 10])
Inplace Addition x.add_(y) = tensor([10, 10, 10])  <- Value of x will be updated and y will remain same
Now, value of x : tensor([10, 10, 10])


### Subtraction

In [18]:
# Subtraction
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

print('x - y =', x-y)

x - y = tensor([-8, -6, -4])


### Division

In [19]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

z = x/y  # element wise division
print('z =', z)

z = tensor([0.1111, 0.2500, 0.4286])


### Exponential

In [20]:
z = x.pow(2)  # Element wise raising power
print('x.pow(2) :', z)

# We can perform same operation like foll
z = x ** 2
print('x ** 2 =', z)

x.pow(2) : tensor([1, 4, 9])
x ** 2 = tensor([1, 4, 9])


### Extra

In [21]:
z = x > 0
print('x > 0 =', z)

x > 0 = tensor([True, True, True])


### Matrix Multiplication

In [22]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

x3 = torch.mm(x1, x2)   # Output will of size 2x3
print('torch.mm(x1, x22) :\n',x3)

x3 = x1.mm(x2)

torch.mm(x1, x22) :
 tensor([[2.1647, 1.0205, 1.8849],
        [1.5448, 1.3492, 1.8805]])


In [23]:
# Performing A x A x A

a = torch.rand(3,3)
a.matrix_power(3)  # AxAxA, output size will be 3x3
print('AxAxA =', a)

AxAxA = tensor([[0.3385, 0.4008, 0.3123],
        [0.0825, 0.1968, 0.8483],
        [0.0123, 0.4717, 0.3529]])


In [24]:
# Dot product

z = torch.dot(x, y)
print('Dot product =', z)

Dot product = tensor(46)


In [25]:
# Batch Matrix Multiplication

batch_size = 32
n = 10
m = 20
p = 30

t1 = torch.rand((batch_size, n, m))
t2 = torch.rand((batch_size, m, p))
out = torch.bmm(t1, t2)
print('Batch Multiplication :\n', out)

Batch Multiplication :
 tensor([[[4.8570, 5.6794, 4.4128,  ..., 4.6306, 5.2864, 4.4817],
         [5.2713, 6.3025, 4.9063,  ..., 4.1950, 5.0330, 5.1803],
         [4.6610, 5.6852, 5.1100,  ..., 4.9656, 5.1416, 5.0448],
         ...,
         [4.4870, 4.8119, 4.7845,  ..., 4.7916, 4.6403, 3.3851],
         [5.3169, 6.0678, 5.3803,  ..., 5.2443, 5.1624, 4.5075],
         [4.5816, 4.3874, 4.6410,  ..., 5.0637, 4.3793, 4.0335]],

        [[4.1036, 5.7213, 4.9280,  ..., 5.5183, 4.8738, 4.2537],
         [5.0719, 6.4843, 7.0456,  ..., 6.6320, 5.2123, 5.7406],
         [5.2390, 6.3421, 6.7604,  ..., 6.3028, 5.2766, 5.7213],
         ...,
         [3.9658, 5.0545, 5.0947,  ..., 5.2005, 4.4287, 4.4493],
         [4.7100, 6.4480, 5.5007,  ..., 6.4452, 5.3504, 5.0711],
         [4.5815, 5.6666, 5.0698,  ..., 6.1211, 4.2861, 4.8395]],

        [[4.1599, 3.9667, 3.6323,  ..., 4.2452, 4.1019, 3.4182],
         [3.2672, 3.6962, 3.3464,  ..., 3.6147, 2.9910, 3.0853],
         [4.7883, 5.4026, 4.5575, 

## Broadcasting

In [26]:
x1 = torch.rand((5, 5))  # 5x5 Matrix
v = torch.rand((1, 5))  #1x5 Matrix or Vector ( 1 row, 5 cols)

z  = x1 - v  # the vector becomes 5x5, one row repeated 5 times

print('x1 - v = ', z)

z = x1 ** v  # Vector v becomes 5x5, one row repeated 5 times

print('x1 ** v = ', z)

x1 - v =  tensor([[ 0.1341, -0.1859,  0.4890,  0.2916,  0.6124],
        [-0.2816, -0.6218, -0.1393, -0.3534, -0.0686],
        [ 0.1008,  0.1886,  0.1019, -0.1996,  0.7849],
        [ 0.5000, -0.0858,  0.3378,  0.3009,  0.5015],
        [-0.1478,  0.0152, -0.4033, -0.1533,  0.5741]])
x1 ** v =  tensor([[0.7930, 0.6192, 0.9980, 0.9062, 0.9591],
        [0.4626, 0.1447, 0.6022, 0.4051, 0.6768],
        [0.7720, 0.9087, 0.7776, 0.5595, 0.9924],
        [0.9936, 0.7019, 0.9181, 0.9116, 0.9343],
        [0.5906, 0.7810, 0.3171, 0.5993, 0.9509]])


## Other Operations

In [27]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print('Matrix X :\n', x)

sum_x = torch.sum(x, dim = 0)  # Take sum of Matrix v along dimension = 0
print('Sum along Dimension 0 :\n', sum_x)

Matrix X :
 tensor([[1, 2, 3],
        [4, 5, 6]])
Sum along Dimension 0 :
 tensor([5, 7, 9])


### Get Maximum and Minimum

In [28]:
x = torch.tensor([
    [1, 2, 3],
    [6, 7, 8],
    [10, 14, 15]
])

vals, indices = torch.max(x, dim=0)
print('Max - vals = {0}, indices = {1}'.format(vals, indices))


vals, indices = torch.min(x, dim=0)
print('Min - vals = {0}, indices = {1}'.format(vals, indices))

Max - vals = tensor([10, 14, 15]), indices = tensor([2, 2, 2])
Min - vals = tensor([1, 2, 3]), indices = tensor([0, 0, 0])


### Get Absolute value

In [29]:
x = -(torch.rand(3, 4))
print('X is :\n', x)
print('torch.abs(x) :\n', torch.abs(x))

X is :
 tensor([[-0.1950, -0.0024, -0.6750, -0.1497],
        [-0.5007, -0.5524, -0.7166, -0.1580],
        [-0.5832, -0.8637, -0.8987, -0.8270]])
torch.abs(x) :
 tensor([[0.1950, 0.0024, 0.6750, 0.1497],
        [0.5007, 0.5524, 0.7166, 0.1580],
        [0.5832, 0.8637, 0.8987, 0.8270]])


In [30]:
x = torch.tensor([
    [1, 2, 3],
    [6, 7, 8],
    [10, 14, 15]
])


z = torch.argmax(x)
print('Argmax of x : ', z)

Argmax of x :  tensor(8)


### Element wise comparison

In [31]:
x = torch.rand(3, 3)
y = torch.rand(3, 3)

z = torch.eq(x, y)

print('torch.eq(x, y) :\n', z)  # Checks if elements are equal

torch.eq(x, y) :
 tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


### Sort Tensor

In [32]:
sorted_z, indices = torch.sort(y, dim=0, descending=False)  
# Sort Tensor along dimension 0
print(sorted_z, indices)

tensor([[0.6347, 0.3796, 0.3104],
        [0.7366, 0.8239, 0.3852],
        [0.8538, 0.9217, 0.7261]]) tensor([[0, 0, 1],
        [2, 1, 0],
        [1, 2, 2]])


### Like ReLu

In [33]:
#  Check all elements of X. If element is less than a min value then set it to 0

x = torch.tensor([
    [1, -2, 3],
    [-6, 7, 8],
    [10, -14, 15]
])

z = torch.clamp(x, min=0)
print(z)

tensor([[ 1,  0,  3],
        [ 0,  7,  8],
        [10,  0, 15]])


## Tensor Indexing

In [34]:
batch_size = 5
features = 4
x = torch.rand((batch_size, features))

print('X :\n', x)

print(x[0].shape)  # x[0, :] -> 0th row, all columns(all features)
print(x[:, 0].shape)

X :
 tensor([[0.5748, 0.1341, 0.0322, 0.5308],
        [0.1659, 0.7520, 0.9542, 0.2423],
        [0.0602, 0.7253, 0.6680, 0.3695],
        [0.0973, 0.9195, 0.9954, 0.4714],
        [0.9920, 0.1772, 0.8205, 0.9937]])
torch.Size([4])
torch.Size([5])


### Fancy Indexing

In [35]:
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices])

x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows, cols]) # First selects rows then columns. Picks 1 row then 0th row

tensor([2, 5, 8])
tensor([0.0749, 0.5236])


### Advance indexing

In [36]:
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])
print(x[(x > 2) & (x > 8)])
print(x[x.remainder(2)==0])

tensor([0, 1, 9])
tensor([9])
tensor([0, 2, 4, 6, 8])


### Useful Operations

In [37]:
print(torch.where(x > 5, x, x*2))

print('Print Unique Values :', torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique())

print('Print Dimension of Matrix :',x.ndimension())  # if 5x5x5 then it will return -> 5 Dim

print('Count number of values using x.numel() :',x.numel()) # Count num of values

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
Print Unique Values : tensor([0, 1, 2, 3, 4])
Print Dimension of Matrix : 1
Count number of values using x.numel() : 10


## Reshape Tensors

In [38]:
x = torch.arange(9)

x_3x3 = x.view(3, 3)  # Acts on Contigous tensors
print('x_3x3 (using view) : ', x_3x3)

x_3x3 = x.reshape(3, 3)  # Makes copy. Always work. Little slow

x_3x3 (using view) :  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [39]:
y = x_3x3.t()  #Transpose
print('Transpose of x_3x3 :\n', y)

Transpose of x_3x3 :
 tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [40]:
# - If view() doesnt work then the tensor is not contiguous. Then
print(y.contiguous().view(9))  # Convert Tensor to contiguous Tensor first

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


## Concatenate

In [41]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)  # Concatenate
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


## Unroll the elements

In [42]:
# Unroll the elements, have 10 elements instead of 2*5
z = x1.view(-1) # Flatten the tensor
print(z.shape)

torch.Size([10])


In [43]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

torch.Size([64, 10])


## Switch Axes

In [44]:
# Switch the axes. Keep batch but exchange 2 5 to 5 2
z = x.permute(0, 2, 1)  # keep 0 dimension to 0, 2nd dimension as 1st and 1st dimension as 2nd
print(z.shape)

torch.Size([64, 5, 2])


In [45]:
x = torch.arange(10)
#  make 1x10 vector
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)  # to have 10x1 vector

torch.Size([1, 10])
torch.Size([10, 1])


In [46]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)  # 1x1x10

z = x.squeeze(0)  # to remove 1st 1
print(z.shape)

torch.Size([1, 10])
